---

- name: Setup Fog Server
  hosts: 127.0.0.1
  connection: local
  vars:
      fog_user: fog
      fog_user_password: "password"
      mysql_password: "password"
      mariadb_root_password: "{{ mysql_password }}"
      fog_settings:
          dns: 1.1.1.1
          os:
              RedHat: 1
              Debian: 2
          install_dhcp: false
          storage_location: "/images"
  roles:
      - mariadb-server
      - fog-server
