---

- name: Install sudo
  package:
    name: sudo
    state: present

- name: Create FOG user
  user:
    name: "{{ fog_user  }}"
    shell: /bin/bash
    group: wheel
    append: yes
    createhome: yes

- name: Install Firewalld
  package:
    name: firewalld
    state: present

- name: Allow FOG Project services
  firewalld:
    service: "{{ item }}"
    zone: public
    state: enabled
    permanent: yes
  with_items:
    - http
    - https
    - tftp
    - ftp
    - mysql
    - nfs
    - mountd
    - rpc-bind
    - proxy-dhcp
    - samba
    - dhcp
    - dns

- name: Allow possible used ports for fog multicast
  firewalld:
    port: 49152-65532/udp
    zone: public
    state: enabled
    permanent: yes

- name: Clone FOG
  git:
    repo: https://github.com/FOGProject/fogproject.git
    dest: "/home/{{ fog_user  }}/fog"
    version: "{{ fog_branch  }}"

- name: copy over install template
  template:
    src: fogpriorconfig.j2
    dest: "/home/{{ fog_user  }}/install_settings"

- name: Install FOG
  shell: "./installfog.sh -Y -f /home/{{ fog_user }}/install_settings <<< $'{{ mariadb_root_password }}\n'"
  args:
    chdir: "/home/{{ fog_user  }}/fog/bin"
    creates: /opt/fog/.fogsettings

- name: Remove Install template
  file:
    path: "/home/{{ fog_user  }}/install_settings"
    state: absent
